// edges — inbound cross-file edge snapshot + re-link (issue #288 split).
//
// A changed file's symbol purge (`mutate::purge_file_symbols`) would orphan
// any resolved edge whose TARGET sits inside it. This module snapshots those
// inbound edges before the purge and re-inserts them after the re-parse, so a
// resolved graph's cross-file edges survive an incremental pass.

use std::collections::HashSet;

use crate::graph_store::{cypher_str, GraphStore, REL_TABLES};

/// One captured inbound edge whose target sits in a modified file and whose
/// source sits elsewhere, saved so the purge does not orphan it.
pub(super) struct SavedEdge {
    table: &'static str,
    source_id: String,
    target_id: String,
    confidence: String,
    resolution_method: String,
}

/// Prefixes of the resolution rel tables — the only tables that carry cross-file
/// edges (structural Defines/HasMethod/… are intra-file and re-emitted by the
/// re-parse). Mirrors `graph_store::is_resolution_rel`, kept local so this
/// module reasons from the public `REL_TABLES` list alone.
const RESOLUTION_PREFIXES: &[&str] = &[
    "Imports_",
    "Calls_",
    "Implements_",
    "Extends_",
    "Uses_",
    "References_",
];

/// Snapshots inbound cross-file edges into the symbols of `changed_rels`.
///
/// Captures an edge iff its target is a symbol inside a changed file
/// (`starts_with(t.id, "<rel>::")`) and its source's owning file is NOT in
/// `reparsed_set` (an edge from another re-parsed file is regenerated by that
/// file's own re-parse/re-link, so re-linking it here would be redundant). At
/// the index stage AP produces no cross-file symbol-targeted edges, so this
/// captures nothing; it becomes load-bearing the moment the graph also carries
/// resolved edges (a resolve_graph pass, or a future resolved artifact), which
/// is exactly the case the C reference's snapshot exists for.
pub(super) fn snapshot_inbound_edges(
    store: &GraphStore,
    changed_rels: &[&str],
    reparsed_set: &HashSet<String>,
) -> Result<Vec<SavedEdge>, String> {
    let mut saved = Vec::new();
    if changed_rels.is_empty() {
        return Ok(saved);
    }
    // One `starts_with(t.id, 'p1') OR starts_with(t.id, 'p2') …` predicate covers
    // every changed file at once, so the scan costs one query per resolution
    // table instead of one per (table × file).
    let target_predicate = changed_rels
        .iter()
        .map(|rel| format!("starts_with(t.id, {})", cypher_str(&format!("{rel}::"))))
        .collect::<Vec<_>>()
        .join(" OR ");

    for &(name, _from, to) in REL_TABLES.iter() {
        if !is_resolution_table(name) {
            continue;
        }
        // File/Directory-targeted edges never need snapshotting: those nodes
        // are kept across a modification, so inbound edges survive structurally.
        if to == "File" || to == "Directory" {
            continue;
        }
        let cypher = format!(
            "MATCH (s)-[r:{name}]->(t) WHERE {target_predicate} \
             RETURN s.id, t.id, r.confidence, r.resolution_method"
        );
        let qr = store.execute_query(&cypher)?;
        for row in qr.rows {
            if row.len() < 2 {
                continue;
            }
            let source_id = row[0].clone();
            let target_id = row[1].clone();
            // Skip edges whose source is itself being re-parsed.
            if reparsed_set.contains(&owning_file(&source_id)) {
                continue;
            }
            saved.push(SavedEdge {
                table: name,
                source_id,
                target_id,
                confidence: row.get(2).cloned().unwrap_or_default(),
                resolution_method: row.get(3).cloned().unwrap_or_default(),
            });
        }
    }
    Ok(saved)
}

/// Re-inserts each snapshotted edge whose endpoints both still exist. A missing
/// endpoint makes `insert_edge`'s MATCH…MATCH…CREATE a no-op (target symbol was
/// deleted/renamed by the edit) — matching full-reindex semantics, which would
/// also not produce an edge to a vanished symbol.
pub(super) fn relink_inbound_edges(store: &GraphStore, saved: &[SavedEdge]) -> Result<(), String> {
    for e in saved {
        let conf = if e.confidence.trim().is_empty() {
            "1.0".to_string()
        } else {
            e.confidence.clone()
        };
        let method = cypher_str(&e.resolution_method);
        let props: Vec<(&str, &str)> = vec![("confidence", &conf), ("resolution_method", &method)];
        // Best-effort: a schema mismatch on one edge must not abort the pass.
        if let Err(err) = store.insert_edge(e.table, &e.source_id, &e.target_id, &props) {
            eprintln!(
                "incremental: relink {} {} -> {} skipped: {err}",
                e.table, e.source_id, e.target_id
            );
        }
    }
    Ok(())
}

/// The repo-relative file that a node id belongs to: the substring before the
/// first `"::"` for a symbol, or the whole id for a File/Directory node.
fn owning_file(id: &str) -> String {
    match id.find("::") {
        Some(i) => id[..i].to_string(),
        None => id.to_string(),
    }
}

/// True for a resolution rel table (carries cross-file edges).
fn is_resolution_table(name: &str) -> bool {
    RESOLUTION_PREFIXES.iter().any(|p| name.starts_with(p))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn owning_file_splits_on_first_separator() {
        assert_eq!(owning_file("src/a.rs::foo::bar"), "src/a.rs");
        assert_eq!(owning_file("src/a.rs"), "src/a.rs");
        assert_eq!(owning_file("src/a.rs::call@10:2#3-9"), "src/a.rs");
    }

    #[test]
    fn resolution_tables_recognised() {
        assert!(is_resolution_table("Calls_Function_Function"));
        assert!(is_resolution_table("Imports_File_File"));
        assert!(!is_resolution_table("Defines_File_Function"));
        assert!(!is_resolution_table("Contains_Dir_File"));
    }
}
